# Generated by Django 3.1 on 2022-05-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20220518_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('analysedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_cons', to='api.ordonnance')),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docteur_cons', to=settings.AUTH_USER_MODEL)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_cons', to='api.ordonnance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_cons', to=settings.AUTH_USER_MODEL)),
                ('radiodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_cons', to='api.ordonnance')),
            ],
        ),
    ]
