# Generated by Django 3.1 on 2022-05-23 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
