# Generated by Django 3.1 on 2022-05-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='analysedata',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='radiodata',
        ),
    ]
