# Generated by Django 3.1 on 2022-05-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220526_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='description',
            new_name='consDescription',
        ),
    ]
