# Generated by Django 3.1 on 2022-06-01 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_rapportmedical'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='nomLaboratoire',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='radiologue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiologue_rad', to=settings.AUTH_USER_MODEL),
        ),
    ]
