# Generated by Django 3.1 on 2022-06-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220601_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportmedical',
            name='donnee',
            field=models.FileField(blank=True, default='', null=True, upload_to='data/rapport-data/rapport-files/'),
        ),
    ]
