# Generated by Django 3.1 on 2022-05-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, 'cardiologue'), (31, 'dentiste'), (32, 'generaliste'), (33, 'ophtalmologue')], null=True),
        ),
    ]
