# Generated by Django 3.1 on 2022-04-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20220413_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('homme', 'homme'), ('femme', 'femme')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('admin', 'Admin'), ('patient', 'Patient'), ('docteur', 'Docteur'), ('infermier', 'Infermier'), ('accueil', 'Accueil')], default=2, null=True),
        ),
    ]
