# Generated by Django 3.1 on 2022-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20220529_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Patient'), (3, 'Docteur'), (4, 'Infermier'), (5, 'Accueil'), (6, 'RADIOLOGUE'), (7, 'ANALYSTE'), (8, 'PHARMACIEN')], null=True),
        ),
    ]
