# Generated by Django 3.1 on 2022-04-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20220414_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(11, 'homme'), (22, 'femme')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Patient'), (3, 'Docteur'), (4, 'Infermier'), (5, 'Accueil')], default=2, null=True),
        ),
    ]
