# Generated by Django 3.1 on 2022-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20220414_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Patient'), (3, 'Docteur'), (4, 'Infermier'), (5, 'Accueil')], null=True),
        ),
    ]
